/* eslint-disable react/no-children-prop */
import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import CustomLayout from "../customLayout";
import { AuthContextProvider } from "../context/auth";
import { SchoolProvider } from "../context/school";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "School App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-white${inter.className}`}>
        <AuthContextProvider>
          <SchoolProvider>
            <CustomLayout children={children} />
          </SchoolProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
